### ISSUE TITLE
Questions on options and outputs

### ISSUE THREAD

**Issue by jeancarlier34** [songlab-cal/soapswga#9]
Hello Jane,

I have been using your SWGA2 soft for few weeks and posted before some issues. Since I have not received answers, I have just removed them because there were may be too long and I'm giving a summary here:
- It is not possible to use a fg genome in several chromosomes. The program works only when you give a single fasta file with all the chromosomes as a single sequence.
- I did not find the min_GC and max_GC options presented page 5 of your preprint article. That's right?
- I used max_gini=0.6 but in the output files step2_df.csv and step3_df.csv primers with Gini index > 0.6 are still present. Are these primers filtered later in the process? A possibility to get around the problem is to filter  primers with Gini index > 0.6 in the step2_df.csv file and then to run again step 3 and 4. Does this make sens?
- Could you please explain me what are the values given with the Final top sets (see example below) and what could be the range of good values?

FINAL TOP SETS FROM ALL RESTARTS: 10
[AGGCTAATA, ATAGGCTAA, TAGGCTAAT], 1.82
[AGGCTAATA, AGTAGTAGTA, ATAGGCTAA, TAGGCTAAT, TATAGGCTA], 1.8
[AATAGGCTA, AGGCTAATA, AGTAGTAGTA, ATAGGCTAA, TAATAGGCT, TAGGCTAAT, TATAGGCTA], 1.76
[AATAGGCTA, AGGCTAATA, AGTAGTAGTA, ATAGGCTAA, TAATAGGCT, TAGGCTAAT, TATAGGCTA], 1.76
[AATAGGCTA, AGGCTAATA, AGTAGTAGTA, ATAGGCTAA, TAATAGGCT, TAGGCTAAT, TATAGGCTA], 1.76
[AATAGGCTA, AGGCTAATA, AGTAGTAGTA, ATAGGCTAA, TAATAGGCT, TAGGCTAAT, TATAATACG], 1.65
[AATAGGCTA, ATAGGCTAA, TAATAGGCT, TAGGCTAAT, TATAGGCTA], 1.62
[AGGCTAATA, ATAGGCTAA, CGGTATATA, TAGGCTAAT], 1.59
[AGGCTAATA, ATAGGCTAA, CGGTATATA, TAGGCTAAT], 1.59
[ATAGGCTAA, TAGGCTAAT, TATAGGCTA], 1.56

Thanks in advance for your answer,
Kind regards,
Jean

**Comment by jeancarlier34** [comment]
Hi again,
Sorry there are several mistakes in my previous message.

Actually in the step2_df.csv file the primers are repeated 25 times, corresponding to the number of fg_genomes. So that's could be the reason. I tried to use a single fasta file with all the chromosome but I got an error. Is there an other solution?

The options min_GC and max_GC are mentioned in page 5 and not in page 2 in your article.

Thanks in advance for your answer to this and my previous message,
Jean

**Comment by jeancarlier34** [comment]
Hello,
I have not received an answer but I could find a solution for the first issue, combining all the fg chromosome as a single ones.

However I found an other issue. I used these parameters:
Parameters:
json_file: ./params_pf_all_chr2.json
data_dir: /shared/home/jcarlier/pop_gen_in_p_fijiensis/swga/all_chr2/
src_dir: /shared/home/jcarlier/softs/swga2/src/
min_fg_freq: 1e-05
max_bg_freq: 5e-06
min_tm: 15
max_tm: 45
max_gini: 0.6
max_primer: 500
min_amp_pred: 10
cpus: 16
max_dimer_bp: 3
max_self_dimer_bp: 4
fg_genomes: ['/shared/home/jcarlier/reference/Mycfi2_chr/concat_chr.fa']
bg_genomes: ['/shared/home/jcarlier/reference/Pahang_chr/chr01.fa', '/shared/home/jcarlier/reference/Pahang_chr/chr02.fa', '/shared/home/jcarlier/reference/Pahang_chr/chr03.fa', '/shared/home/jcarlier/reference/Pahang_chr/chr04.fa', '/shared/home/jcarlier/reference/Pahang_chr/chr05.fa', '/shared/home/jcarlier/reference/Pahang_chr/chr06.fa', '/shared/home/jcarlier/reference/Pahang_chr/chr07.fa', '/shared/home/jcarlier/reference/Pahang_chr/chr08.fa', '/shared/home/jcarlier/reference/Pahang_chr/chr09.fa', '/shared/home/jcarlier/reference/Pahang_chr/chr10.fa', '/shared/home/jcarlier/reference/Pahang_chr/chr11.fa']
fg_prefixes: ['/shared/home/jcarlier/pop_gen_in_p_fijiensis/swga/all_chr2/kmer_file/pf/concat_chr.fa']
bg_prefixes: ['/shared/home/jcarlier/pop_gen_in_p_fijiensis/swga/all_chr2/kmer_file/banana/chr01.fa', '/shared/home/jcarlier/pop_gen_in_p_fijiensis/swga/all_chr2/kmer_file/banana/chr02.fa', '/shared/home/jcarlier/pop_gen_in_p_fijiensis/swga/all_chr2/kmer_file/banana/chr03.fa', '/shared/home/jcarlier/pop_gen_in_p_fijiensis/swga/all_chr2/kmer_file/banana/chr04.fa', '/shared/home/jcarlier/pop_gen_in_p_fijiensis/swga/all_chr2/kmer_file/banana/chr05.fa', '/shared/home/jcarlier/pop_gen_in_p_fijiensis/swga/all_chr2/kmer_file/banana/chr06.fa', '/shared/home/jcarlier/pop_gen_in_p_fijiensis/swga/all_chr2/kmer_file/banana/chr07.fa', '/shared/home/jcarlier/pop_gen_in_p_fijiensis/swga/all_chr2/kmer_file/banana/chr08.fa', '/shared/home/jcarlier/pop_gen_in_p_fijiensis/swga/all_chr2/kmer_file/banana/chr09.fa', '/shared/home/jcarlier/pop_gen_in_p_fijiensis/swga/all_chr2/kmer_file/banana/chr10.fa', '/shared/home/jcarlier/pop_gen_in_p_fijiensis/swga/all_chr2/kmer_file/banana/chr11.fa']
mismatch_penalty: 4
verbose: False
drop_iterations: 4
iterations: 8
top_set_count: 10
retries: 5
max_sets: 5
selection_metric: deterministic
fg_circular: False
bg_circular: False
fg_seq_lengths: [73638457]
bg_seq_lengths: [41765374, 34826099, 43931233, 45086258, 46513039, 43117521, 39373400, 51314288, 47719527, 40511255, 34663808]

And I got this result:
Computing foreground and background rates...
Filtered 1260091 number of primers based on foreground/background rate.
Computing Gini index...
Filtered 0 number of primers based on gini rate.
Number of remaining primers: 500

However either in step2_df.csv and the step3_df.csv there are still primer with a Gini index > max_gini:

[step2_df.csv](https://github.com/songlab-cal/swga2/files/10229518/step2_df.csv)
[step3_df.csv](https://github.com/songlab-cal/swga2/files/10229521/step3_df.csv)

So the primers with Gini index >  max_gini seem to be not removed. Or may be they are removed latter in the process.

Thanks for your answer,
Jean

**Comment by janeyubear** [comment]
Hi there, so sorry for not getting to your questions! 

>It is not possible to use a fg genome in several chromosomes. The program works only when you give a single fasta file with all the chromosomes as a single sequence.
	
Unfortunately, yes, they would need to be piped into the same file. However, this might be pretty easily done if you have them all in the same folder and use `cat` (https://www.baeldung.com/linux/concatenate-files or https://www.biostars.org/p/127239/).

>I did not find the min_GC and max_GC options presented page 5 of your preprint article. That's right?

These should actually be automatic and not parameters to the program: "Motifs with GC content less than min_GC or greater than max_GC (default 0.375 and 0.625, respectively), as well as motifs with three or more G/C in the last five base pairs of the 3′-end, are eliminated."

>I used max_gini=0.6 but in the output files step2_df.csv and step3_df.csv primers with Gini index > 0.6 are still present. Are these primers filtered later in the process? A possibility to get around the problem is to filter primers with Gini index > 0.6 in the step2_df.csv file and then to run again step 3 and 4. Does this make sense?

Could you perhaps provide the command you are using for Step 2? 

>Could you please explain me what are the values given with the Final top sets (see example below) and what could be the range of good values?

It's tricky to give absolute values that are good since I'm not sure which genomes you're using and the model is calibrated to Mycobacterium and Human. I would look at the relative values and pick the best sets depending on their size/desired diversity.

**Comment by jeancarlier34** [comment]
Many thanks for your answer. Yes I could run the program putting all the chromosome of the fg genome in the same fasta file.
Please find here the files of one example of the analysis I run: 

[log.out.txt](https://github.com/songlab-cal/swga2/files/10399223/log.out.txt)
[params_pf_chr_all.json.txt](https://github.com/songlab-cal/swga2/files/10399224/params_pf_chr_all.json.txt)
[step3_df.csv](https://github.com/songlab-cal/swga2/files/10399225/step3_df.csv)
[step2_df.csv](https://github.com/songlab-cal/swga2/files/10399226/step2_df.csv)

As you could see in the json file, max_gini = 0.6.
However, in the log.out file it is written:

"Computing foreground and background rates...
Filtered 1273869 number of primers based on foreground/background rate.
Computing Gini index...
Filtered 0 number of primers based on gini rate.
Number of remaining primers: 683" 

And in the step2_df.csv and step3_df.csv files primers with Gini index > 0.6 are still present. So, to get around this problem I filtered primers with Gini index > 0.6 in the step2_df.csv file using excel and then I run again step 3 and 4 with swga2 in an other analysis. Here are the files of the corresponding analysis. 

[log2_23.out.txt](https://github.com/songlab-cal/swga2/files/10399568/log2_23.out.txt)
[params_pf_all_chr2_23.json.txt](https://github.com/songlab-cal/swga2/files/10399569/params_pf_all_chr2_23.json.txt)
[step3_df.csv](https://github.com/songlab-cal/swga2/files/10399570/step3_df.csv)
[step2_df.csv](https://github.com/songlab-cal/swga2/files/10399573/step2_df.csv)

Does this make sense?

I'm using the soft with the genome of a fungal banana pathogen (P. fijiensis) of 74 Mb as fg genome and the banana genome of 550 Mb as bg genome. Does it make sense to use a model calibrated to Mycobacterium and Human with these organisms? 

Thanks in advance for your answer.
Best regards,
Jean

**Comment by janeyubear** [comment]
Hi Jean, 

Thanks for your patience! I'm not sure I entirely understand the problem because when I download the first step2_df.csv I see that all the primers have a gini value < 0.6. Could you clarify what you had to do in excel manually? 

There is evidence that the model can extrapolate to other genomes, but the absolute raw values may not be normalized to the same scale--you'd have to look at them relative to the rest of the scored sets. For example, we also applied [this method to P. melaninogenica](https://www.biorxiv.org/content/10.1101/2022.04.27.489632v1.full)  successully and in [this paper](https://www.medrxiv.org/content/10.1101/2022.09.06.22279552v1), they've applied it to Leishmania instead of Mycobacterium.

**Comment by jeancarlier34** [comment]
Hi Jane,
Thanks for you answer. Sorry I made a mistake when I downloaded the files. Here are the good one for the first analysis:
[log2_20.out.txt](https://github.com/songlab-cal/swga2/files/10421191/log2_20.out.txt)
[params_pf_all_chr2_20.json.txt](https://github.com/songlab-cal/swga2/files/10421192/params_pf_all_chr2_20.json.txt)
[step3_df.csv](https://github.com/songlab-cal/swga2/files/10421193/step3_df.csv)
[step2_df_1.csv](https://github.com/songlab-cal/swga2/files/10421194/step2_df_1.csv)

In the log.out file it is written:
"Computing foreground and background rates...
Filtered 1273869 number of primers based on foreground/background rate.
Computing Gini index...
Filtered 0 number of primers based on gini rate.
Number of remaining primers: 683"

And as you could see in the step2_df.csv and step3_df.csv files primers with Gini index > 0.6 are still present. So I extract primers with Gini <0.6 and I run the second analysis given in my previous message with the filtered step2_df.csv. 

Thanks,
Jean

**Comment by janeyubear** [comment]
Hi Jean, 

Thank you for the correct file! I believe I have fixed the issue in the latest commit, but you'll need to do ANY of the three below:

1. Replace line 236 in swga/src/filter.py from `return df` to `return df[df['gini_bool']]`
2. Replace the contents of swga/src/filter.py after copy/pasting everything from https://github.com/songlab-cal/swga2/blob/master/src/filter.py
3. Replace the whole swga2 directory. 

Please let me know if that doesn't help!

**Comment by Alexharrott** [comment]
@janedwivedi I have re-downloaded the swga2 to have the latest commit for the mini_filtering. 


On step 2 candidate primer filtering I now have the following error: 


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gini_df["ratio"] = gini_df["bg_count"] / gini_df["fg_count"]

Do you think this is a result of the latest changes? 

Thank you.

**Comment by Wentaochenn** [comment]
@janedwivedi Hi Jane,

I found it still doesn't work. I got the following message below:

Computing Gini index...
Filtered 0 number of primers based on gini rate.

Hoping to get your reply.

Thanks,
Wentao
